// Hind Build Real Services Seed Data
// Auto-synced and comprehensive with verified media, rich details, process, and SEO

export const HBS_SERVICES_SEED = [
  {
    "serviceNumber": "01",
    "title": "Structure Repair",
    "hindiTitle": "संरचना मरम्मत एवं मजबूतीकरण",
    "slug": "structure-repair",
    "shortDescription": "Specialized crack injection, RCC column strengthening, structural restoration, and beam reinforcement for residential and commercial structures.",
    "fullDescription": "Hind Build delivers certified civil engineering diagnostics and structural rehabilitation across Rajasthan. Utilizing non-destructive evaluation, ultrasonic pulse velocity checks, and rebound hammer testing, our team assesses load-bearing concrete frames before deploying restorative solutions. Using low-viscosity structural epoxy injection, high-strength polymer-modified mortars (PMM), micro-concreting jackets, and anti-corrosion rebar passivators, we restore structural load capacities and extend building lifespans without disruptive reconstruction.",
    "image": "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&q=85",
    "icon": "ShieldAlert",
    "features": "[\"RCC Column & Beam Micro-Concrete Jacketing\",\"Low-Viscosity Epoxy & Polyurethane Crack Injection\",\"Rebar Rust Passivation & Zinc-Rich Coating\",\"Load-Bearing Masonry & Foundation Underpinning\"]",
    "benefits": "[\"Restores structural safety and load distribution to aged concrete\",\"Arrests active cracking before catastrophic slab deflection occurs\",\"Extends the operational lifespan of residential and commercial buildings\",\"Engineered compliance with Indian Standard (IS) 13935 restoration codes\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Non-Destructive Structural Survey\",\"desc\":\"Inspection of crack patterns, structural deflection, and hollow zones using calibrated rebound hammers.\"},{\"step\":\"02\",\"title\":\"Surface Chipping & Rebar Exposure\",\"desc\":\"Careful removal of spalled concrete to expose corroded rebar without compromising adjacent sound concrete.\"},{\"step\":\"03\",\"title\":\"Chemical Treatment & Port Installation\",\"desc\":\"Rust conversion primer on steel bars and mechanical installation of injection packers along crack lines.\"},{\"step\":\"04\",\"title\":\"High-Pressure Injection & Micro-Concreting\",\"desc\":\"Injection of structural epoxy resin under pressure, followed by polymer-modified mortar application.\"},{\"step\":\"05\",\"title\":\"Curing & Load Integrity Verification\",\"desc\":\"Controlled wet curing and post-treatment tap testing to verify structural continuity.\"}]",
    "warrantyDetails": "Up to 5-Year written workmanship and bond warranty on reinforced structural concrete repairs.",
    "pricingEstimate": "Itemized per running foot for crack injection, and per cubic foot for micro-concrete beam/column repairs following site audit.",
    "faqs": "[{\"q\":\"How do I know if a wall crack is structural or cosmetic?\",\"a\":\"Hairline plaster cracks smaller than 0.5mm are usually cosmetic. However, diagonal cracks near door/window corners, stepped masonry cracks, or horizontal cracks along beams and columns indicate structural movement requiring engineering inspection.\"},{\"q\":\"Can RCC column repairs be performed while the building is occupied?\",\"a\":\"Yes. Our structural technicians deploy temporary hydraulic prop jacks to relieve dead loads during concrete chipping and jacketing, allowing safe continued occupancy.\"},{\"q\":\"What materials do you use for structural repairs?\",\"a\":\"We exclusively specify certified industrial formulations from Sika, Fosroc, and Dr. Fixit, including non-shrink free-flow micro-concretes and structural bonding epoxies.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80\",\"https://images.unsplash.com/photo-1541888946425-d0fbb18615f8?w=800&q=80\",\"https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&q=85",
    "whatsappCtaText": "Hello Hind Build, I need an engineer to inspect structural cracks and concrete damage at my property.",
    "active": true,
    "order": 1,
    "metaTitle": "Structure Repair & RCC Strengthening | Hind Build Bhilwara",
    "metaDescription": "Certified RCC column strengthening, crack injection, and structural rehabilitation services in Bhilwara & Rajasthan by Hind Build. Call +91 75970 00601."
  },
  {
    "serviceNumber": "02",
    "title": "Water Leakage Solution",
    "hindiTitle": "वाटर लीकेज एवं सीलन समाधान",
    "slug": "water-leakage-solution",
    "shortDescription": "Permanent waterproofing and moisture barrier solutions for roofs, basements, wet walls, and bathrooms without destructive breaking.",
    "fullDescription": "Eliminate wall dampness, paint peeling, salt efflorescence (shora), and persistent ceiling drips permanently. Hind Build applies scientific diagnostic methods, utilizing pinless electronic moisture meters and thermal imaging cameras to locate hidden water travel paths behind tiles, slabs, and concealed pipe runs. We engineer both positive-side and negative-side waterproofing barriers using multi-layer elastomeric polyurethane membranes, polymer cementitious crystalline barriers, and hydrophilic injection grouts.",
    "image": "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?q=80&w=1200&auto=format&fit=crop",
    "icon": "Droplets",
    "features": "[\"Terrace Multi-Layer Elastomeric Waterproofing\",\"Wall Dampness & Efflorescence (Shora) Remediation\",\"Negative-Side Basement Hydrophobic Pressure Grouting\",\"Bathrooms & Concealed Sunken Slab Leakage Sealing\"]",
    "benefits": "[\"Prevents ceiling discoloration, peeling paint, and mould formation\",\"Shields internal reinforcement bars from corrosion induced by moisture\",\"Non-destructive testing pinpoints leak origins without breaking floors\",\"High-elongation UV-resistant coatings withstand harsh Rajasthan summers\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Electronic Moisture Profiling\",\"desc\":\"Non-destructive scanning of floor slabs and walls to identify sub-surface moisture saturation.\"},{\"step\":\"02\",\"title\":\"Substrate Preparation & Washing\",\"desc\":\"High-pressure jet washing, algae removal, and V-groove routing along construction joints and parapet junctions.\"},{\"step\":\"03\",\"title\":\"Polymer Base Primer & Sealing\",\"desc\":\"Deep-penetrating primer applied to seal concrete capillaries and create molecular bonding.\"},{\"step\":\"04\",\"title\":\"Reinforced Membrane Application\",\"desc\":\"Application of 2 coats of elastomeric polyurethane or acrylic polymer reinforced with non-woven fiber mesh.\"},{\"step\":\"05\",\"title\":\"Ponding Test & Final Handover\",\"desc\":\"48-hour water ponding test to physically verify 100% watertight integrity before handover.\"}]",
    "warrantyDetails": "Up to 5 to 7-Year written leak-free warranty on terrace and wet area waterproofing systems.",
    "pricingEstimate": "Rates start from ₹45 - ₹85 per sq.ft depending on substrate condition, membrane specification, and area size.",
    "faqs": "[{\"q\":\"Can you fix bathroom ceiling leaks without breaking the upstairs tiles?\",\"a\":\"In many cases, yes. If the leak stems from joint grout degradation or trap seal failures, we apply crystalline penetration chemicals and epoxy joint grouting without tile removal.\"},{\"q\":\"Why does white powder (shora) keep coming out of my ground floor walls?\",\"a\":\"This is rising capillary dampness carrying ground mineral salts. Hind Build installs chemical DPC (damp-proof course) injection barriers to permanently block rising moisture.\"},{\"q\":\"How long does a terrace waterproofing treatment take to cure?\",\"a\":\"Surface drying takes 4–6 hours per coat. Full curing takes 48 hours, followed by our mandatory 48-hour water ponding verification test.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=800&q=80\",\"https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&q=80\",\"https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I am experiencing water seepage and leakage at my building and need a diagnostic inspection.",
    "active": true,
    "order": 2,
    "metaTitle": "Water Leakage & Waterproofing Solutions | Hind Build Bhilwara",
    "metaDescription": "Permanent roof terrace, basement, and bathroom waterproofing with electronic leak detection in Bhilwara & Rajasthan by Hind Build. 5-Year Warranty."
  },
  {
    "serviceNumber": "03",
    "title": "Plumbing & Electrical",
    "hindiTitle": "प्लंबिंग एवं इलेक्ट्रिकल कार्य",
    "slug": "plumbing-and-electrical",
    "shortDescription": "Concealed pipeline leak detection, CPVC/UPVC pipe repairs, sanitization fixtures, and comprehensive sanitary maintenance.",
    "fullDescription": "Recurring plumbing breakdowns lead to concealed water wastage, damp walls, and low pressure. Hind Build deploys master plumbers equipped with acoustic pipe listening devices and pressure gauges to locate concealed pipe fractures. From CPVC and UPVC hot/cold line replacements to drainage stack alignment and automatic pressure booster pump systems, our team ensures durable, sanitary water flow throughout your property.",
    "image": "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?q=80&w=1200&auto=format&fit=crop",
    "icon": "Wrench",
    "features": "[\"Concealed Pipe Leak Pinpointing & Acoustic Detection\",\"CPVC, UPVC & SWR Pipeline Overhauls\",\"Pressure Booster Pump Installation & Servicing\",\"Sanitary Fixture Upgrades & Drainage De-Clogging\"]",
    "benefits": "[\"Eliminates mystery water meter surges and concealed pipe leaks\",\"Ensures optimal shower and faucet pressure across multi-storey floors\",\"Prevents hazardous backflow and foul sewer odors into living areas\",\"High-grade branded valves and solvent cement joints prevent future joints failure\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Pressure Testing & Acoustic Scan\",\"desc\":\"Isolating plumbing lines with pneumatic pressure pumps to identify drop rates and pinpoint break locations.\"},{\"step\":\"02\",\"title\":\"Targeted Minimal Opening\",\"desc\":\"Making micro-chases in wall masonry directly at the fault point, avoiding wide destructive breaking.\"},{\"step\":\"03\",\"title\":\"Pipe Section Replacement\",\"desc\":\"Replacing brittle or fractured lines with heavy-duty SDR 11 CPVC pipes and brass transition fittings.\"},{\"step\":\"04\",\"title\":\"Hydraulic Pressure Check\",\"desc\":\"Testing the repaired loop under 10 bar water pressure for 60 minutes to confirm joint integrity.\"},{\"step\":\"05\",\"title\":\"Plaster & Tile Restitution\",\"desc\":\"Restoring chased masonry with polymer mortar and color-matching adjacent tiles.\"}]",
    "warrantyDetails": "1-Year workmanship warranty on all newly installed sanitary lines and pressure booster pumps.",
    "pricingEstimate": "Transparent diagnostic inspection fee with itemized line-item BOQ for material and pipe replacements.",
    "faqs": "[{\"q\":\"How do you detect a hidden leak behind bathroom tiles?\",\"a\":\"We run a line isolation test with a hydrostatic pressure pump and pinpoint the exact fissure using acoustic ground microphones and thermal sensors.\"},{\"q\":\"What causes low water pressure on the upper floors?\",\"a\":\"Common causes include air locks in the overhead tank line, internal scaling in galvanized pipes, or undersized gravity headers. We install properly calibrated automated booster systems.\"},{\"q\":\"Do you supply the replacement pipes and valves?\",\"a\":\"Yes. We source genuine ISI-certified pipes (Astral, Ashirvad, Supreme) or accommodate client-supplied materials based on your preference.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&q=80\",\"https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&q=80\",\"https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I have an urgent plumbing issue / pipe leak and need a technician to evaluate.",
    "active": true,
    "order": 3,
    "metaTitle": "Plumbing & Sanitary Repair Services | Hind Build Bhilwara",
    "metaDescription": "Concealed pipeline leak detection, CPVC/UPVC pipe repairs, booster pumps, and sanitary maintenance in Bhilwara by Hind Build. Call +91 75970 00601."
  },
  {
    "serviceNumber": "04",
    "title": "Painting & Wall Repair",
    "hindiTitle": "पेंटिंग एवं वॉल रिपेयर",
    "slug": "painting-and-wall-repair",
    "shortDescription": "Weatherproof exterior elastomeric coatings, anti-fungal interior luxury finishes, and plaster crack remediation.",
    "fullDescription": "Rajasthan's intense thermal fluctuations and monsoon humidity demand paint systems engineered for elasticity and UV protection. Hind Build delivers turnkey painting and wall revitalization, beginning with mechanical surface scraping, moisture barrier priming, and fiber-reinforced crack bridging. We apply high-performance exterior weather-shield coatings and anti-fungal interior luxury emulsions that resist peeling, algae growth, and fading for years.",
    "image": "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=1200&auto=format&fit=crop",
    "icon": "Paintbrush",
    "features": "[\"Exterior Elastomeric Weatherproof Emulsions\",\"Anti-Fungal & Anti-Bacterial Interior Luxury Finishes\",\"Plaster Crack Remediation & Putty Skimming\",\"Texture Coating & Protective Wall Sealants\"]",
    "benefits": "[\"Bridges micro-cracks on exterior facades, preventing rainwater ingress\",\"High solar reflectance keeps indoor temperatures cooler in summer\",\"Anti-fungal formulation prevents dark mildew and algae staining on walls\",\"Clean execution with full floor and furniture masking protection\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Moisture & Substrate Check\",\"desc\":\"Checking wall surface moisture levels before painting to guarantee paint adhesion.\"},{\"step\":\"02\",\"title\":\"Scraping & Plaster Rectification\",\"desc\":\"Mechanized sanding to remove loose paint and filling structural cracks with polymer paste.\"},{\"step\":\"03\",\"title\":\"Alkali-Resistant Primer Coat\",\"desc\":\"Application of deep-penetrating primer to neutralize wall alkalinity and seal surface pores.\"},{\"step\":\"04\",\"title\":\"Double Coat Putty Skimming\",\"desc\":\"Applying 2 coats of polymer-modified white cement putty followed by fine sanding.\"},{\"step\":\"05\",\"title\":\"Dual Finish Coats & Inspection\",\"desc\":\"Applying 2 roller coats of branded premium emulsion (Asian Paints / Berger) and quality sign-off.\"}]",
    "warrantyDetails": "3 to 5-Year anti-peeling and color-retention warranty on branded exterior elastomeric coatings.",
    "pricingEstimate": "Transparent per sq.ft rates for scraping, putty, primer, and dual coat exterior or interior painting.",
    "faqs": "[{\"q\":\"Why does paint peel off in patches near baseboards?\",\"a\":\"This is caused by rising dampness or water seepage behind the plaster. Painting over damp plaster will fail within months; we treat the moisture source with a chemical barrier before applying paint.\"},{\"q\":\"Do your painters cover furniture and floors?\",\"a\":\"Yes. Every project includes comprehensive masking with plastic drop sheets and masking tape on all floors, switches, and woodwork.\"},{\"q\":\"Which paint brands do you apply?\",\"a\":\"We apply authentic premium grades from Asian Paints (Apex Ultima, Royale), Berger (WeatherCoat), and Dulux, with batch seals verified on site.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&q=80\",\"https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=800&q=80\",\"https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I want to get an itemized quote for interior / exterior painting for my property.",
    "active": true,
    "order": 4,
    "metaTitle": "Interior & Exterior Painting Services | Hind Build Bhilwara",
    "metaDescription": "Weatherproof exterior coatings, crack remediation, and luxury interior painting in Bhilwara & Rajasthan by Hind Build. 5-Year Warranty."
  },
  {
    "serviceNumber": "05",
    "title": "Terrace & Bird Protection",
    "hindiTitle": "छत एवं पक्षी सुरक्षा",
    "slug": "terrace-and-bird-protection",
    "shortDescription": "UV-stabilized anti-bird netting, pigeon spikes, solar panel bird guards, and heat-reflective terrace floor treatments.",
    "fullDescription": "Pigeons and birds cause severe aesthetic fouling, acidic concrete degradation, and health risks from droppings. Hind Build provides humane, non-lethal, high-durability bird exclusion systems across residential balconies, HVAC shafts, factory sheds, and solar rooftop installations. Using UV-resistant high-density polyethylene netting anchored with marine-grade stainless steel cables and polycarbonate-base spikes, we secure openings without obstructing light or airflow.",
    "image": "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1200&auto=format&fit=crop",
    "icon": "Bird",
    "features": "[\"UV-Stabilized High-Density Balcony & Shaft Netting\",\"304-Grade Stainless Steel Bird Spikes for Ledges & AC Units\",\"Solar Panel Underside Mesh Barrier Installation\",\"Terrace Solar Reflective High-Albedo Sealants\"]",
    "benefits": "[\"Eliminates corrosive bird droppings that eat into waterproof coatings and AC coils\",\"Prevents respiratory health risks associated with accumulated pigeon droppings\",\"Maintains 100% natural ventilation and unobstructed outdoor balcony views\",\"UV-stabilized materials withstand continuous 45°C+ summer sun without sagging\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Elevation & Duct Measurement\",\"desc\":\"Surveying balcony perimeters, building shafts, and AC outdoor unit ledges.\"},{\"step\":\"02\",\"title\":\"Perimeter Wire Rope Anchoring\",\"desc\":\"Installing stainless steel eye-bolts and high-tension wire rope along opening boundaries.\"},{\"step\":\"03\",\"title\":\"Bird Net Tensioning & Clipping\",\"desc\":\"Fixing UV-stabilized net to boundary ropes with galvanized hog-rings, ensuring zero gaps.\"},{\"step\":\"04\",\"title\":\"Ledge Spike Fixing\",\"desc\":\"Securing 304 stainless steel spike strips on narrow parapets and AC frames using polyurethane adhesive.\"},{\"step\":\"05\",\"title\":\"Inspection & Clean-Up\",\"desc\":\"Checking tension uniformity and cleaning installation debris.\"}]",
    "warrantyDetails": "3-Year replacement warranty on netting against UV degradation and wire rope detachment.",
    "pricingEstimate": "Calculated per square foot for balcony netting and per running foot for stainless steel spike strips.",
    "faqs": "[{\"q\":\"Does bird netting block sunlight or balcony airflow?\",\"a\":\"No. Our netting utilizes 0.8mm to 1mm ultra-thin high-tensile twine with 1-inch mesh openings, making it virtually invisible from a short distance while permitting complete airflow and sunlight.\"},{\"q\":\"Do the spikes hurt or kill birds?\",\"a\":\"No. The spikes feature blunt rounded tips that create an un-landable surface, safely deterring birds without causing injury.\"},{\"q\":\"Can monkeys or rodents chew through the netting?\",\"a\":\"For areas with monkey activity, we install reinforced heavy-duty wire-mesh or stainless steel core netting designed to withstand pulling and chewing.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80\",\"https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=800&q=80\",\"https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I need bird netting and pigeon spikes installed at my balcony / building.",
    "active": true,
    "order": 5,
    "metaTitle": "Balcony Bird Netting & Pigeon Spikes | Hind Build Bhilwara",
    "metaDescription": "Professional balcony bird netting, stainless steel spikes, and rooftop protection in Bhilwara & Rajasthan by Hind Build. 3-Year Warranty."
  },
  {
    "serviceNumber": "06",
    "title": "Termite Control",
    "hindiTitle": "दीमक एवं कीट नियंत्रण",
    "slug": "termite-control",
    "shortDescription": "Pre-construction & post-construction drill-and-fill chemical termite barriers with comprehensive warranty guarantees.",
    "fullDescription": "Subterranean termites silently devastate wooden door frames, wardrobes, and furniture before their presence is visible. Hind Build delivers scientific drill-and-inject anti-termite barriers adhering to IS 6313 specifications. We drill precise 12mm holes along interior walls, door frames, and foundation perimeters, injecting government-approved, low-odor termiticides that create an impassable protective chemical zone around your property.",
    "image": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1200&auto=format&fit=crop",
    "icon": "Bug",
    "features": "[\"Post-Construction Drill-Inject-Seal Floor Perimeter Treatment\",\"Door Frame & Concealed Woodwork In-Depth Chemical Barrier\",\"External Plinth Perimeter Soil Trench Chemical Impregnation\",\"Pre-Construction Foundation Soil Treatment (IS 6313 Part 2)\"]",
    "benefits": "[\"Permanently halts termite colony access from underground soil nests\",\"Protects expensive modular furniture, doors, documents, and wardrobes\",\"Utilizes low-odor, non-repellent chemicals that eliminate entire colonies\",\"Backed by multi-year written warranty with free scheduled check-ups\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Comprehensive Termite Inspection\",\"desc\":\"Tracing mud tubes, hollow woodwork sounding, and colony entry points throughout the property.\"},{\"step\":\"02\",\"title\":\"Precision Perimeter Drilling\",\"desc\":\"Drilling 12mm holes at 1-foot intervals along skirting walls and door junctions.\"},{\"step\":\"03\",\"title\":\"Pressurized Chemical Injection\",\"desc\":\"Injecting certified termiticide emulsion (Imidacloprid / Chlorpyrifos formulation) under controlled pressure.\"},{\"step\":\"04\",\"title\":\"Color-Matched Hole Sealing\",\"desc\":\"Sealing all drilled holes with white cement and pigment to restore floor aesthetics.\"},{\"step\":\"05\",\"title\":\"Woodwork Surface Spraying\",\"desc\":\"Spraying chemical barrier on the backsides of wardrobes and wooden paneling.\"}]",
    "warrantyDetails": "5-Year written chemical warranty on post-construction drill-and-inject anti-termite treatments.",
    "pricingEstimate": "Calculated based on total built-up area in square feet and the number of wooden door and window frames treated.",
    "faqs": "[{\"q\":\"Is the termite treatment chemical safe for children and pets?\",\"a\":\"Yes. We use advanced odorless termiticides approved by Central Insecticides Board. The chemical is injected beneath the floor slabs and into walls, leaving zero open residue in the living air.\"},{\"q\":\"Will drilling holes damage my marble or vitrified tiles?\",\"a\":\"Our operators use diamond-tipped masonry drill bits at skirt junctions. The holes are small (12mm) and are filled and color-matched immediately after chemical injection, making them barely noticeable.\"},{\"q\":\"What happens if termites reappear during the warranty period?\",\"a\":\"If any termite activity returns in treated areas during the 5-year warranty period, Hind Build provides 100% free re-treatment under our written warranty.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80\",\"https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&q=80\",\"https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I have discovered termites at my property and need an inspection and treatment.",
    "active": true,
    "order": 6,
    "metaTitle": "Anti-Termite Treatment & Pest Defense | Hind Build Bhilwara",
    "metaDescription": "Govt-approved drill-inject-seal anti-termite treatment with 5-year written warranty in Bhilwara & Rajasthan by Hind Build. Call +91 75970 00601."
  },
  {
    "serviceNumber": "07",
    "title": "Tile Work",
    "hindiTitle": "टाइल एवं फ्लोरिंग कार्य",
    "slug": "tile-work",
    "shortDescription": "Hollow tile regrouting, broken tile replacements, epoxy grouting, vitrified flooring, and anti-skid bathroom solutions.",
    "fullDescription": "Hollow sounding tiles, cracked bathroom slabs, and discolored joint grout ruin the appearance and hygiene of a building. Hind Build delivers precision tiling, substrate re-leveling, and chemical epoxy regrouting. Our skilled masons resolve hollow tile detachment using low-viscosity polymer re-bonding without destroying surrounding tiles, install large-format vitrified slabs with laser leveling, and apply waterproof epoxy grout that resists stains and mold.",
    "image": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1200&auto=format&fit=crop",
    "icon": "Layers",
    "features": "[\"Stain-Proof Chemical Epoxy Tile Regrouting\",\"Hollow & Popping Tile Non-Destructive Polymeric Re-Bonding\",\"Large-Format Vitrified & Ceramic Floor Tile Laying\",\"Anti-Skid Terrace & Bathroom Floor Upgrades\"]",
    "benefits": "[\"Prevents water ingress through deteriorated tile joints into ceiling slabs\",\"Fixes sounding hollow tiles before they crack under heavy foot pressure\",\"Epoxy grout is 100% waterproof, acid-resistant, and easy to sanitize\",\"Laser-guided alignment ensures flush joints without lippage or unevenness\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Tap Sounding & Joint Inspection\",\"desc\":\"Acoustic tap testing across floor areas to identify hollow or loose tiles.\"},{\"step\":\"02\",\"title\":\"Old Grout Mechanical Raking\",\"desc\":\"Raking out degraded cement grout to a minimum depth of 3mm without chipping tile edges.\"},{\"step\":\"03\",\"title\":\"Joint Deep Vacuuming\",\"desc\":\"Cleaning dust and moisture out of open joints using industrial vacuums.\"},{\"step\":\"04\",\"title\":\"Epoxy Chemical Compounding\",\"desc\":\"Mixing 3-part resin, hardener, and colored filler per manufacturer ratios.\"},{\"step\":\"05\",\"title\":\"Rubber Float Packing & Clean Off\",\"desc\":\"Packing joints solid with rubber floats and final sponge wash before setting.\"}]",
    "warrantyDetails": "2-Year bond warranty against hollow tile detachment and epoxy joint dislodgement.",
    "pricingEstimate": "Transparent per sq.ft laying rate or fixed repair charge for localized tile replacement and regrouting.",
    "faqs": "[{\"q\":\"Why do my bathroom floor tile joints keep turning black?\",\"a\":\"Traditional white cement grout absorbs water, body oils, and soap scum, promoting fungal growth. Hind Build removes old cement grout and installs 100% waterproof epoxy grout that never discolors.\"},{\"q\":\"Can hollow floor tiles be fixed without breaking them?\",\"a\":\"Yes. If the tiles are not cracked, we drill micro-holes in the joints and inject high-bond polymer adhesive under low pressure to refill the hollow void underneath.\"},{\"q\":\"How long after epoxy regrouting can we use the bathroom?\",\"a\":\"Epoxy grout sets to foot traffic within 24 hours and reaches full chemical water cure in 48 hours.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80\",\"https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?w=800&q=80\",\"https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I need tile repair / epoxy regrouting services at my property.",
    "active": true,
    "order": 7,
    "metaTitle": "Tile Repair & Epoxy Regrouting Services | Hind Build Bhilwara",
    "metaDescription": "Epoxy regrouting, hollow tile re-bonding, and vitrified flooring repair in Bhilwara & Rajasthan by Hind Build. Call +91 75970 00601."
  },
  {
    "serviceNumber": "08",
    "title": "AC, Lift & Solar",
    "hindiTitle": "एसी, लिफ्ट एवं सोलर सिस्टम",
    "slug": "ac-lift-and-solar",
    "shortDescription": "Rooftop solar panel maintenance, HVAC/AC chemical coil cleaning, elevator safety inspection, and duct services.",
    "fullDescription": "Electro-mechanical systems represent vital operational infrastructure in modern residential apartments and commercial buildings. Hind Build provides integrated preventative maintenance covering split, cassette, and ductable AC chemical deep cleaning and gas charging; rooftop solar PV panel de-soiling and inverter electrical efficiency checks; and coordinated elevator mechanical maintenance audits to ensure peak efficiency and zero downtime.",
    "image": "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=1200&q=85",
    "icon": "Sun",
    "features": "[\"Solar Panel High-Pressure De-Soiling & Output Auditing\",\"Split & Cassette AC Jet Pump Chemical Coil Cleaning\",\"Refrigerant Leak Detection & Gas Re-Charging\",\"Elevator Mechanical Safety Audit & AMC Coordination\"]",
    "benefits": "[\"Restores solar PV generation output by up to 25% through dust removal\",\"Lowers monthly AC electricity consumption and improves indoor cooling\",\"Prevents hazardous compressor burnout and refrigerant oil degradation\",\"Single-point engineering coordination eliminates multiple contractor calls\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Diagnostic Performance Audit\",\"desc\":\"Measuring solar inverter kilowatt output, AC air velocity, and temperature drop.\"},{\"step\":\"02\",\"title\":\"Safety Isolation\",\"desc\":\"Isolating high-voltage DC solar breakers and AC distribution circuits.\"},{\"step\":\"03\",\"title\":\"Chemical Deep Cleaning\",\"desc\":\"Applying non-corrosive chemical foam on AC coils and de-ionized water washing on solar glass.\"},{\"step\":\"04\",\"title\":\"Electrical Resistance & Gas Check\",\"desc\":\"Testing grounding earthing resistance and checking refrigerant pressure.\"},{\"step\":\"05\",\"title\":\"Performance Re-Measurement\",\"desc\":\"Documenting restored solar generation wattage and AC cooling delta.\"}]",
    "warrantyDetails": "90-Day service warranty on AC gas charging and chemical coil cleaning.",
    "pricingEstimate": "Fixed per-unit servicing packages with transparent component replacement estimates.",
    "faqs": "[{\"q\":\"How frequently should rooftop solar panels be cleaned in Rajasthan?\",\"a\":\"Due to high dust and particulate levels in central Rajasthan, solar panels should be washed every 15 to 20 days. Uncleaned panels can lose up to 30% of their power generation capacity.\"},{\"q\":\"What does AC chemical jet servicing include?\",\"a\":\"It includes dismantling indoor unit casing, high-pressure jet pump cleaning of the cooling coil and blower, outdoor condenser coil chemical wash, drain pipe clearing, and refrigerant pressure check.\"},{\"q\":\"Do you provide Annual Maintenance Contracts (AMC)?\",\"a\":\"Yes. Hind Build offers customized commercial and residential AMC packages covering quarterly servicing, emergency callouts, and preventive electrical audits.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=800&q=80\",\"https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80\",\"https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=1200&q=85",
    "whatsappCtaText": "Hello Hind Build, I need servicing for my AC / rooftop solar system / elevator.",
    "active": true,
    "order": 8,
    "metaTitle": "Solar Panel & HVAC AC Maintenance | Hind Build Bhilwara",
    "metaDescription": "Rooftop solar panel cleaning, AC chemical servicing, and electro-mechanical maintenance in Bhilwara by Hind Build. Call +91 75970 00601."
  },
  {
    "serviceNumber": "09",
    "title": "Electrical & Machine Work",
    "hindiTitle": "इलेक्ट्रिकल एवं मशीन वर्क",
    "slug": "electrical-and-machine-work",
    "shortDescription": "Three-phase load balancing, short-circuit diagnostics, MCB/DB upgrades, diesel generator & motor maintenance.",
    "fullDescription": "Electrical anomalies pose severe fire hazards and appliance breakdown risks. Hind Build deploys licensed electricians equipped with thermal imaging cameras and digital insulation testers (meggers) to diagnose overloaded phases, loose neutral connections, and earth leakages. From complete distribution board (DB) replacements and three-phase industrial balancing to water pump motors and generator maintenance, we engineer absolute safety into your wiring.",
    "image": "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=1200&auto=format&fit=crop",
    "icon": "Zap",
    "features": "[\"Distribution Board (DB) & MCB/RCCB Overhauls\",\"Thermal Imaging Overload & Hot-Spot Diagnostics\",\"Three-Phase Load Balancing & Earth Resistance Testing\",\"Submersible Motor & Water Pump Rewinding & Servicing\"]",
    "benefits": "[\"Prevents electrical fires by identifying hidden loose connections and hot spots\",\"Residual Current Circuit Breaker (RCCB) installation protects against fatal shocks\",\"Balances phase loads, reducing neutral heating and voltage fluctuations\",\"Restores energy efficiency and prevents repeated appliance motor burnouts\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Thermal Scan & Phase Audit\",\"desc\":\"Thermal imaging of main panels to spot elevated temperature at terminals and breakers.\"},{\"step\":\"02\",\"title\":\"Insulation & Earth Test\",\"desc\":\"Testing line insulation with 500V Megger and verifying earthing pit resistance below 5 ohms.\"},{\"step\":\"03\",\"title\":\"Breaker & Wiring Replacement\",\"desc\":\"Upgrading sub-standard MCBs with certified C-curve breakers and replacing heat-damaged cabling.\"},{\"step\":\"04\",\"title\":\"Phase Load Redistribution\",\"desc\":\"Re-routing heavy appliance circuits to achieve uniform ampere draw across all three phases.\"},{\"step\":\"05\",\"title\":\"Test Load Run & Safety Handover\",\"desc\":\"Operating full building loads for 30 minutes with clamp meter re-verification.\"}]",
    "warrantyDetails": "1-Year warranty on newly wired distribution boards and commercial switchgear installations.",
    "pricingEstimate": "Fixed diagnostic rate plus itemized quotation for circuit breakers, wiring, and motor overhauls.",
    "faqs": "[{\"q\":\"Why does my main MCB trip frequently even without heavy loads?\",\"a\":\"Frequent tripping usually indicates an earth leakage, neutral-earth loop fault, or an aging breaker with weakened bimetallic strips. We test the circuit with a clamp meter and insulation tester to isolate the culprit.\"},{\"q\":\"What is an RCCB and why is it essential?\",\"a\":\"An RCCB (Residual Current Circuit Breaker) detects micro-current leakages to earth and trips within 30 milliseconds, protecting family members from fatal electrical shocks and preventing electrical fires.\"},{\"q\":\"Do you test chemical earthing pits?\",\"a\":\"Yes. We measure earth resistance with a digital Earth Tester and re-condition dry pits with bentonite compound and chemical electrodes.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80\",\"https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&q=80\",\"https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I have an electrical fault / panel issue and need a licensed electrician.",
    "active": true,
    "order": 9,
    "metaTitle": "Electrical Panel & Machine Work | Hind Build Bhilwara",
    "metaDescription": "Distribution board upgrades, three-phase load balancing, and thermal electrical audit in Bhilwara by Hind Build. Call +91 75970 00601."
  },
  {
    "serviceNumber": "10",
    "title": "Safety & Compliance",
    "hindiTitle": "सुरक्षा एवं अनुपालन",
    "slug": "safety-and-compliance",
    "shortDescription": "Fire extinguisher servicing, smoke detection systems, fire exit compliance, lightning arrester testing, and structural audits.",
    "fullDescription": "Commercial establishments, residential societies, and industrial premises in Rajasthan must satisfy state safety directives and fire safety standards. Hind Build conducts complete safety and statutory compliance audits. Our engineers inspect fire fighting equipment, refill and hydro-test ABC/CO2 extinguishers, service smoke alarms and wet risers, test lightning arresters, and issue documented engineering inspection certificates.",
    "image": "https://images.unsplash.com/photo-1582139329536-e7284fece509?q=80&w=1200&auto=format&fit=crop",
    "icon": "ShieldCheck",
    "features": "[\"Fire Extinguisher Refilling, Hydro-Testing & Audit\",\"Smoke, Heat Detector & Alarm Panel Testing\",\"Lightning Arrester & Early Streamer Emission (ESE) Inspections\",\"Emergency Exit Photoluminescent Signage & Illumination\"]",
    "benefits": "[\"Ensures life-safety compliance for commercial and multi-family buildings\",\"Guarantees fire extinguishers operate reliably with certified pressure checks\",\"Protects rooftop machinery and occupants from seasonal lightning strikes\",\"Provides documented safety certificates required for statutory renewals\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Comprehensive Safety Walkthrough\",\"desc\":\"Auditing all fire points, evacuation routes, and electrical hazards against National Building Code (NBC).\"},{\"step\":\"02\",\"title\":\"Cylinder Pressure & Weight Check\",\"desc\":\"Checking extinguisher gauge pressures, nozzle hoses, and weighing gas cartridges.\"},{\"step\":\"03\",\"title\":\"Hydrostatic Testing & Refill\",\"desc\":\"Testing expired cylinder shells under water pressure and refilling with fresh dry chemical powder.\"},{\"step\":\"04\",\"title\":\"Lightning Arrester Grounding Test\",\"desc\":\"Testing rooftop copper/ESE arrester conductivity down to dedicated earth pits.\"},{\"step\":\"05\",\"title\":\"Certification & Tagging\",\"desc\":\"Affixing verified inspection tags on all units and providing digital audit documentation.\"}]",
    "warrantyDetails": "Certified hydrostatic pressure test certificates and standard compliance logs provided.",
    "pricingEstimate": "Annual maintenance contracts (AMC) and per-cylinder refilling or testing schedules.",
    "faqs": "[{\"q\":\"How frequently must fire extinguishers be serviced?\",\"a\":\"Portable fire extinguishers must undergo mandatory visual pressure inspection every quarter and complete chemical refilling/servicing annually.\"},{\"q\":\"Is lightning protection mandatory for buildings in Rajasthan?\",\"a\":\"Buildings higher than 15 meters or properties housing expensive rooftop solar and HVAC machinery should have certified lightning arresters per IS/IEC 62305 to avoid equipment destruction.\"},{\"q\":\"Do you provide fire exit evacuation signage?\",\"a\":\"Yes. We install photoluminescent (glow-in-the-dark) signage and battery-backed emergency LED lights along exit staircases.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1582139329536-e7284fece509?w=800&q=80\",\"https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80\",\"https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1582139329536-e7284fece509?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I need a fire safety audit / extinguisher refilling at my commercial property.",
    "active": true,
    "order": 10,
    "metaTitle": "Building Fire Safety & Compliance Audit | Hind Build Bhilwara",
    "metaDescription": "Fire extinguisher servicing, smoke detection testing, and lightning protection audits in Bhilwara by Hind Build. Call +91 75970 00601."
  },
  {
    "serviceNumber": "11",
    "title": "Gardening",
    "hindiTitle": "गार्डनिंग एवं लैंडस्केप रखरखाव",
    "slug": "gardening",
    "shortDescription": "Lawn grooming, vertical gardens, automatic drip irrigation repair, organic fertilization, and seasonal pruning.",
    "fullDescription": "Healthy landscape greens and rooftop terrace gardens elevate property quality and temperature comfort. Hind Build delivers horticulturally sound garden maintenance and landscape care. Our team handles lawn aeration, turf mowing, tree pruning, soil enrichment with organic vermicompost, pest-defense sprays, and the setup or repair of automated drip irrigation networks to conserve water in arid climates.",
    "image": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=1200&auto=format&fit=crop",
    "icon": "Flower2",
    "features": "[\"Lawn Mowing, Dethatching & Turf Renovation\",\"Automated Drip Irrigation Setup & Valve Repairs\",\"Rooftop Terrace Planting & Vertical Bio-Walls\",\"Organic Pest Defense & Vermicompost Fertilization\"]",
    "benefits": "[\"Reduces terrace surface heat through lush rooftop foliage\",\"Conserves up to 60% water with micro-drip irrigation scheduling\",\"Eliminates fungal plant infections and insect damage with organic remedies\",\"Maintains clean, manicured residential society lawns year-round\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Soil & Vegetation Survey\",\"desc\":\"Evaluating soil pH, sunlight exposure, and plant health conditions across the property.\"},{\"step\":\"02\",\"title\":\"Weeding & Precision Pruning\",\"desc\":\"Clearing parasitic weeds, dead branches, and shaping hedges and ornamental trees.\"},{\"step\":\"03\",\"title\":\"Soil Aeration & Nutrient Feed\",\"desc\":\"Tilling topsoil and applying enriched vermicompost and micronutrient feeds.\"},{\"step\":\"04\",\"title\":\"Irrigation Inspection & Tuning\",\"desc\":\"Testing drip emitter flow rates and setting digital water timers.\"},{\"step\":\"05\",\"title\":\"Preventative Bio-Spraying\",\"desc\":\"Applying neem-based natural pest repellents across all shrub beds.\"}]",
    "warrantyDetails": "Guaranteed healthy plant establishment with replacement terms on landscape installs.",
    "pricingEstimate": "Monthly maintenance retainer plans or project-based lawn and irrigation setup rates.",
    "faqs": "[{\"q\":\"How can I maintain a terrace garden without causing ceiling leaks?\",\"a\":\"Hind Build applies a root-resistant elastomeric waterproofing membrane and installs raised drainage cells beneath planter beds, ensuring 100% water drainage away from the slab.\"},{\"q\":\"Can you automate my garden watering while I am traveling?\",\"a\":\"Yes. We install smart battery-operated digital tap timers connected to micro-drip lines that deliver precise water volume automatically every morning and evening.\"},{\"q\":\"Do you supply seasonal flowering plants in Bhilwara?\",\"a\":\"Yes. We source acclimatized native and seasonal ornamental plants suitable for Rajasthan's climate from verified nurseries.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800&q=80\",\"https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80\",\"https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I need garden maintenance / automated drip irrigation for my property.",
    "active": true,
    "order": 11,
    "metaTitle": "Gardening & Landscape Maintenance | Hind Build Bhilwara",
    "metaDescription": "Lawn grooming, automated drip irrigation, and terrace garden maintenance in Bhilwara & Rajasthan by Hind Build. Call +91 75970 00601."
  },
  {
    "serviceNumber": "12",
    "title": "Cleaning Services",
    "hindiTitle": "गहरी सफाई एवं सैनिटाइजेशन",
    "slug": "cleaning-services",
    "shortDescription": "Post-construction deep cleaning, mechanized floor scrubbing, overhead water tank sanitization, and facade washing.",
    "fullDescription": "Renovation residue, mineral-crusted tiles, and uncleaned water tanks require industrial-grade sanitization. Hind Build delivers mechanized deep cleaning for residential and commercial buildings. We utilize high-pressure water jet blasters, single-disc floor scrubbers, vacuum dust extractors, and food-grade UV tank sterilizers to eliminate cement splatters, paint smears, hard water stains, and microbial biofilms.",
    "image": "https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=1200&auto=format&fit=crop",
    "icon": "Sparkles",
    "features": "[\"Underground & Overhead Water Tank UV Sterilization\",\"Mechanized Single-Disc Floor Scrubbing & Buffing\",\"Post-Renovation Heavy Cement & Paint Residue Extraction\",\"Kitchen Degreasing & Bathroom Scale Removal\"]",
    "benefits": "[\"Ensures safe, odor-free, pathogen-free drinking water from cleaned tanks\",\"Restores original shine to dull, scuffed vitrified tiles and marble floors\",\"Removes fine hazardous silica construction dust from ducts and window tracks\",\"Turnkey move-in readiness with zero effort required from the homeowner\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Sludge Dewatering\",\"desc\":\"Emptying tank sludge using submersible slurry pumps without stirring mud into pipes.\"},{\"step\":\"02\",\"title\":\"High-Pressure Jet Washing\",\"desc\":\"Blasting algae, calcification, and grime off walls and ceilings with 150-bar water jets.\"},{\"step\":\"03\",\"title\":\"Anti-Bacterial Slurry Scrubbing\",\"desc\":\"Scrubbing surfaces with food-grade disinfectant agents.\"},{\"step\":\"04\",\"title\":\"UV Microbial Irradiation\",\"desc\":\"Deploying high-intensity UV lamps inside the dry tank to sterilize suspended bacteria.\"},{\"step\":\"05\",\"title\":\"Post-Cleaning Inspection\",\"desc\":\"Customer walkthrough inspection and completion sign-off.\"}]",
    "warrantyDetails": "100% satisfaction inspection walk-through with on-the-spot touch-up guarantee.",
    "pricingEstimate": "Flat rates based on apartment configuration (1BHK/2BHK/3BHK/Villa) or water tank capacity in liters.",
    "faqs": "[{\"q\":\"How often should underground and overhead water tanks be cleaned?\",\"a\":\"Water tanks should be professionally cleaned and sterilized every 6 months to prevent toxic algae, mosquito larvae, and bacterial biofilms.\"},{\"q\":\"Does post-construction cleaning remove dried cement from window glass?\",\"a\":\"Yes. We use specialized non-scratch glass scrapers and chemical descalers that dissolve dried cement, mortar, and paint droplets without scratching the glass.\"},{\"q\":\"How much time does full home deep cleaning take?\",\"a\":\"A typical 3BHK deep cleaning takes 6–8 hours with a crew of 4 trained technicians and mechanized equipment.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80\",\"https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80\",\"https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I want to book deep cleaning / water tank sanitization for my property.",
    "active": true,
    "order": 12,
    "metaTitle": "Deep Cleaning & Water Tank Sanitization | Hind Build Bhilwara",
    "metaDescription": "Mechanized home deep cleaning, water tank UV sanitization, and post-construction scrubbing in Bhilwara by Hind Build. Call +91 75970 00601."
  },
  {
    "serviceNumber": "13",
    "title": "Packers & Movers",
    "hindiTitle": "पैकर्स एवं मूवर्स",
    "slug": "packers-and-movers",
    "shortDescription": "Safe residential relocation, office shifting, professional multi-layer packaging, and transit insurance support.",
    "fullDescription": "Relocating home or corporate office requires careful packaging and damage-free transit handling. Hind Build delivers disciplined relocation services across Bhilwara and throughout Rajasthan. Our trained crews use heavy-duty corrugated cartons, multi-layer bubble wrap, edge corner protectors, and stretch film. We dismantle delicate furniture, pack electronics securely, load onto enclosed vehicles, and handle complete reassembly at your new destination.",
    "image": "https://images.unsplash.com/photo-1600585152220-90363fe7e115?q=80&w=1200&auto=format&fit=crop",
    "icon": "Truck",
    "features": "[\"Multi-Layer Protective Bubble & Foam Packaging\",\"Modular Furniture & Bed Dismantling and Re-Assembly\",\"Dedicated Enclosed Container Vehicle Transportation\",\"Transit Insurance Support & Complete Inventory Tagging\"]",
    "benefits": "[\"Zero damage handling with heavy-duty foam corner guards on wood and glass\",\"Eliminates personal physical exhaustion during moving days\",\"All boxes numbered and itemized for seamless unpacking room-by-room\",\"Fixed binding quotation with zero surprise charges on delivery day\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Pre-Move Inventory Survey\",\"desc\":\"Cataloging furniture volume, fragile items, and access dimensions at source and destination.\"},{\"step\":\"02\",\"title\":\"Systematic Multi-Layer Packing\",\"desc\":\"Wrapping furniture in bubble film, corrugated sheets, and packing fragile crockery in cushioned cartons.\"},{\"step\":\"03\",\"title\":\"Careful Loading & Lashing\",\"desc\":\"Loading onto enclosed vehicles with internal tie-down straps to prevent transit shifting.\"},{\"step\":\"04\",\"title\":\"Safe Transportation\",\"desc\":\"Direct point-to-point transit with continuous driver communication.\"},{\"step\":\"05\",\"title\":\"Unloading & Reassembly\",\"desc\":\"Unloading, positioning into respective rooms, and reassembling beds and wardrobes.\"}]",
    "warrantyDetails": "Comprehensive transit insurance option and zero-breakage handling protocol.",
    "pricingEstimate": "Distance, volume of goods, and floor height based transparent binding estimates.",
    "faqs": "[{\"q\":\"How are fragile items and electronics protected?\",\"a\":\"Crockery and glassware are wrapped in 3-layer bubble wrap and packed in heavy double-wall corrugated boxes with partition dividers. TVs and appliances are encased in wooden crates or heavy foam wrap.\"},{\"q\":\"Do your movers dismantle and reassemble double beds and wardrobes?\",\"a\":\"Yes. Our team includes experienced carpenters who dismantle beds, wardrobes, and modular units at origin and reassemble them at your new home.\"},{\"q\":\"How far in advance should I book my shifting?\",\"a\":\"We recommend booking 3 to 5 days prior to your preferred shifting date to ensure dedicated vehicle allocation.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&q=80\",\"https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=800&q=80\",\"https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1600585152220-90363fe7e115?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I need a shifting quote for home / office relocation.",
    "active": true,
    "order": 13,
    "metaTitle": "Packers & Movers Relocation Services | Hind Build Bhilwara",
    "metaDescription": "Professional home and office packing, relocation, and furniture moving in Bhilwara & Rajasthan by Hind Build. Call +91 75970 00601."
  },
  {
    "serviceNumber": "14",
    "title": "CCTV & Security",
    "hindiTitle": "सीसीटीवी एवं सुरक्षा प्रणाली",
    "slug": "cctv-and-security",
    "shortDescription": "High-definition IP surveillance, DVR/NVR maintenance, biometric access control, and video intercom installations.",
    "fullDescription": "Protect family members, commercial assets, and perimeter boundaries with reliable electronic security. Hind Build installs and maintains high-definition IP surveillance, night-vision cameras, Network Video Recorders (NVR), biometric door access controllers, and smart video doorbells. We design camera placement angles to eliminate blind spots, configure encrypted remote mobile app viewing, and provide ongoing maintenance.",
    "image": "https://images.unsplash.com/photo-1557597774-9d273605dfa9?q=80&w=1200&auto=format&fit=crop",
    "icon": "Camera",
    "features": "[\"4K & High-Definition IP Surveillance with Night-Vision\",\"NVR / DVR Storage Setup with Remote Smartphone Live Stream\",\"Video Door Phones (VDP) & Intercom Systems\",\"Biometric RFID Access Control & Automated Gate Locks\"]",
    "benefits": "[\"24/7 video recording provides indisputable evidence and crime deterrence\",\"Check live perimeter security feeds from your phone anywhere in the world\",\"Color night-vision cameras ensure crystal-clear vehicle plate capture in pitch darkness\",\"Clean concealed conduit cabling preserves building aesthetics without loose wires\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Security Angle & Blind Spot Survey\",\"desc\":\"Assessing perimeter boundaries, gates, and entry points to specify lens focal lengths.\"},{\"step\":\"02\",\"title\":\"Concealed Cat6 Network Cabling\",\"desc\":\"Running heavy-duty outdoor-rated copper Ethernet cables through concealed PVC conduits.\"},{\"step\":\"03\",\"title\":\"Camera Mounting & Focus Tuning\",\"desc\":\"Mounting weatherproof IP67 cameras and adjusting field-of-view angles.\"},{\"step\":\"04\",\"title\":\"NVR Storage & Cloud Setup\",\"desc\":\"Installing surveillance-grade hard drives and configuring motion-activated recording.\"},{\"step\":\"05\",\"title\":\"Mobile App Configuration\",\"desc\":\"Setting up secure mobile apps on client smartphones with live notification testing.\"}]",
    "warrantyDetails": "1 to 2-Year manufacturer warranty on hardware plus 1-Year Hind Build installation support.",
    "pricingEstimate": "Package pricing per channel (4-camera, 8-camera, 16-camera setups) including cabling and NVR.",
    "faqs": "[{\"q\":\"Can I view my home CCTV cameras when I am out of town?\",\"a\":\"Yes. We configure secure peer-to-peer cloud streaming on your smartphone, enabling real-time HD viewing and playback from anywhere via mobile data.\"},{\"q\":\"How many days of video recordings are saved?\",\"a\":\"Depending on your storage hard drive size (1TB, 2TB, 4TB) and motion-detection settings, systems store between 15 to 45 days of continuous footage before overwriting.\"},{\"q\":\"What brands of surveillance equipment do you install?\",\"a\":\"We install leading certified brands including CP Plus, Hikvision, and Dahua, ensuring genuine warranties and dependable performance.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&q=80\",\"https://images.unsplash.com/photo-1558002038-1055907df827?w=800&q=80\",\"https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1557597774-9d273605dfa9?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I want to install / upgrade CCTV cameras at my property.",
    "active": true,
    "order": 14,
    "metaTitle": "CCTV Installation & Security Systems | Hind Build Bhilwara",
    "metaDescription": "HD IP CCTV cameras, video door phones, and biometric security systems in Bhilwara & Rajasthan by Hind Build. Call +91 75970 00601."
  },
  {
    "serviceNumber": "15",
    "title": "Smart Home Automation",
    "hindiTitle": "स्मार्ट होम ऑटोमेशन",
    "slug": "smart-home-automation",
    "shortDescription": "Smart lighting modules, voice-activated controls, automated curtain motors, and smartphone security integration.",
    "fullDescription": "Transform existing residential and commercial spaces into intelligent, energy-efficient environments without disruptive wall hacking. Hind Build installs modular retrofit smart automation systems that fit behind your existing switchboards. Control lighting ambiance, ceiling fans, air conditioners, motorized curtains, and water tank pumps through smartphone apps or voice commands (Alexa / Google Assistant) from anywhere.",
    "image": "https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=1200&auto=format&fit=crop",
    "icon": "Smartphone",
    "features": "[\"Retrofit Smart Touch Switches (Fits Existing Gang Boxes)\",\"Smartphone App & Voice Assistant (Alexa / Google) Control\",\"Motorized Curtain & Roller Blind Automation\",\"Automated Overhead Water Tank Overflow Cut-Off\"]",
    "benefits": "[\"Zero wall demolition required; smart modules fit behind existing electrical plates\",\"Saves electricity by scheduling lights, geysers, and AC units to turn off automatically\",\"Automated water tank sensors eliminate roof overflow and water wastage completely\",\"Create scheduled scenes such as 'Leaving Home' or 'Goodnight' with one tap\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Existing Switchboard Inspection\",\"desc\":\"Checking neutral wire availability and box depths inside existing electrical switchboards.\"},{\"step\":\"02\",\"title\":\"Micro-Module Retrofitting\",\"desc\":\"Installing compact smart Wi-Fi/Zigbee relays directly behind your existing switch plates.\"},{\"step\":\"03\",\"title\":\"Wi-Fi Gateway & Hub Syncing\",\"desc\":\"Configuring secure local automation gateway for responsive, lag-free switching.\"},{\"step\":\"04\",\"title\":\"Smart Scene Programming\",\"desc\":\"Setting up geyser timers, scheduled outdoor lighting, and voice commands.\"},{\"step\":\"05\",\"title\":\"User Walkthrough & App Handover\",\"desc\":\"Installing the mobile app on all family devices with comprehensive usage guidance.\"}]",
    "warrantyDetails": "2-Year replacement warranty on retrofit smart modules and touch panels.",
    "pricingEstimate": "Per switch-board modular upgrade packages with zero civil wall cutting required.",
    "faqs": "[{\"q\":\"Do I need to rewire my entire house to make it smart?\",\"a\":\"No! Our retrofit automation modules fit directly inside your existing switchboards behind regular switches. Your conventional switches continue to work normally alongside app and voice control.\"},{\"q\":\"What happens if the home Wi-Fi stops working?\",\"a\":\"Your physical wall switches and local automation remotes will continue working normally. The internet connection is only needed when controlling devices from outside the home.\"},{\"q\":\"Can we automate the water pump so the roof tank never overflows?\",\"a\":\"Yes. We install smart water level sensor switches that automatically start the pump when the tank drops below 30% and turn it off the moment it reaches full level.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1558002038-1055907df827?w=800&q=80\",\"https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&q=80\",\"https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I am interested in smart home automation / switch upgrades for my home.",
    "active": true,
    "order": 15,
    "metaTitle": "Smart Home Automation Systems | Hind Build Bhilwara",
    "metaDescription": "Retrofit smart switches, mobile app lighting, and water tank automation in Bhilwara by Hind Build. Call +91 75970 00601."
  },
  {
    "serviceNumber": "16",
    "title": "Furniture Work",
    "hindiTitle": "फर्नीचर एवं काष्ठ कार्य",
    "slug": "furniture-work",
    "shortDescription": "Cabinet repair, wooden door realignment, modular kitchen refurbishment, lock replacements, and custom carpentry.",
    "fullDescription": "Swollen doors that scrape against floors, sagging wardrobe hinges, jammed kitchen pull-out drawers, and degraded laminate edges ruin daily convenience. Hind Build delivers master carpentry and architectural woodwork maintenance. Our carpenters repair swollen doors, upgrade kitchen channels to soft-close telescopic slides, replace damaged laminates with clean edge-banding, and install high-security mortise locks.",
    "image": "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?q=80&w=1200&auto=format&fit=crop",
    "icon": "Armchair",
    "features": "[\"Swollen Wooden Door Plane Shaving & Frame Realignment\",\"Modular Kitchen Soft-Close Telescopic Channel & Hinge Upgrades\",\"Damaged Laminate Pasting & PVC Edge-Banding\",\"High-Security Mortise Lock & Handle Installation\"]",
    "benefits": "[\"Stops irritating door dragging that scratches premium flooring\",\"Smooths sticky modular kitchen drawers with high-durability hardware\",\"Restores structural strength to loose wardrobe shutters and drawer fronts\",\"Skilled master craftsmen equipped with precision power tools for clean work\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Woodwork & Hardware Inspection\",\"desc\":\"Inspecting hinge play, moisture swelling in door bottoms, and drawer misalignment.\"},{\"step\":\"02\",\"title\":\"Dismantling & Precision Planning\",\"desc\":\"Carefully taking down door shutters and planning down excess wood to restore smooth clearance.\"},{\"step\":\"03\",\"title\":\"Heavy-Duty Hardware Replacement\",\"desc\":\"Installing 304-grade stainless steel auto-hinges and soft-close drawer slides.\"},{\"step\":\"04\",\"title\":\"Laminate Re-Bonding & Sealing\",\"desc\":\"Pressing loose laminates with heat adhesive and sealing exposed edges against humidity.\"},{\"step\":\"05\",\"title\":\"Lock Testing & Final Alignment\",\"desc\":\"Lubricating hardware, testing key cylinders, and final balance verification.\"}]",
    "warrantyDetails": "1-Year warranty on newly installed telescopic channels, soft-close hinges, and locks.",
    "pricingEstimate": "Itemized carpenter day-work rates or per-unit refurbishment quotes.",
    "faqs": "[{\"q\":\"Why do wooden doors expand and get jammed during monsoon season?\",\"a\":\"Natural wood and unsealed MDF absorb airborne humidity, causing expansion. Our carpenters plane down the contact edges and apply moisture-resistant sealant on top and bottom door ends to prevent future swelling.\"},{\"q\":\"Can my noisy, sticky kitchen drawers be converted to soft-close?\",\"a\":\"Yes! We replace old roller channels with modern hydraulic soft-close telescopic slides without altering your external cabinet drawer faces.\"},{\"q\":\"Do you fix modular wardrobes that have come off their tracks?\",\"a\":\"Yes. We replace broken bottom rollers and realign sliding door aluminum tracks for smooth operation.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=800&q=80\",\"https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?w=800&q=80\",\"https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I need door repair / modular kitchen carpentry work at my property.",
    "active": true,
    "order": 16,
    "metaTitle": "Carpentry & Furniture Repair Services | Hind Build Bhilwara",
    "metaDescription": "Door realignment, modular kitchen drawer channels, and custom carpentry repairs in Bhilwara by Hind Build. Call +91 75970 00601."
  },
  {
    "serviceNumber": "17",
    "title": "Wall Decor & Wallpaper",
    "hindiTitle": "वॉल डेकोर एवं वॉलपेपर",
    "slug": "wall-decor-and-wallpaper",
    "shortDescription": "Custom wallpaper installation, 3D fluted wall panels, louvers, acoustic padding, and designer accent wall styling.",
    "fullDescription": "Transform dull interior surfaces into sophisticated focal points. Hind Build installs premium imported wallpapers, WPC and charcoal fluted louvers, and textured accent wall paneling. Prior to installation, our technicians test walls for underlying dampness and apply moisture-barrier liners to prevent wallpaper peeling or bubbling. We ensure seamless pattern matching and durable adhesive bonding.",
    "image": "https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?q=80&w=1200&auto=format&fit=crop",
    "icon": "LayoutGrid",
    "features": "[\"Seamless Imported Non-Woven & Vinyl Wallpaper Pasting\",\"Charcoal & WPC Fluted Louver Accent Wall Paneling\",\"Substrate Moisture Testing & Anti-Damp Primer Barrier\",\"Acoustic Padding & Fabric Wall Paneling Installations\"]",
    "benefits": "[\"Instantly elevates living rooms, bedrooms, and offices into luxury spaces\",\"WPC and charcoal panels are 100% termite-proof, borer-proof, and water-resistant\",\"Fluted wall louvers conceal uneven wall plaster and surface imperfections\",\"Non-toxic, odorless wallpaper adhesives allow same-day room occupancy\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Wall Flatness & Moisture Check\",\"desc\":\"Checking wall moisture with electronic meters and filling minor undulations.\"},{\"step\":\"02\",\"title\":\"Oil Primer Base Preparation\",\"desc\":\"Applying oil-based sealant primer to ensure adhesive bonds smoothly without soaking into plaster.\"},{\"step\":\"03\",\"title\":\"Pattern Matching & Precision Slicing\",\"desc\":\"Measuring roll pattern repeats and cutting panels with numbered sequence tags.\"},{\"step\":\"04\",\"title\":\"Adhesive Roller Application\",\"desc\":\"Applying heavy-duty cellulose adhesive with roller and positioning panels seamlessly.\"},{\"step\":\"05\",\"title\":\"Seam Rolling & Air Bubble Extraction\",\"desc\":\"Smoothing out air bubbles with flexible squeegees and rolling seam edges.\"}]",
    "warrantyDetails": "2-Year warranty against adhesive peeling and edge curling on moisture-treated walls.",
    "pricingEstimate": "Per roll installation charge or per sq.ft pricing on charcoal louvers and fluted wall panels.",
    "faqs": "[{\"q\":\"Can wallpaper be applied on a wall with mild dampness?\",\"a\":\"No. Applying wallpaper over damp plaster causes mildew, staining, and peeling within weeks. Hind Build first resolves the underlying dampness with a waterproof chemical barrier before hanging wallpaper.\"},{\"q\":\"What is the lifespan of WPC and charcoal fluted louvers?\",\"a\":\"Charcoal and WPC louvers last over 10 years. They are completely impervious to termites, water, and fading, requiring only gentle wiping.\"},{\"q\":\"Do you supply the wallpaper catalogue?\",\"a\":\"Yes. Our team brings curated sample catalogues featuring textured, geometric, metallic, and botanical themes to your home for selection.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?w=800&q=80\",\"https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&q=80\",\"https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I want to explore wallpaper / fluted louver wall decor for my home.",
    "active": true,
    "order": 17,
    "metaTitle": "Designer Wallpaper & Fluted Wall Louvers | Hind Build Bhilwara",
    "metaDescription": "Imported wallpaper installation, charcoal fluted louvers, and accent wall paneling in Bhilwara by Hind Build. Call +91 75970 00601."
  },
  {
    "serviceNumber": "18",
    "title": "Facade Work (ACP & Glass)",
    "hindiTitle": "फसाड वर्क (एसीपी एवं ग्लास)",
    "slug": "facade-work-acp-glass",
    "shortDescription": "ACP sheet cladding replacement, spider glass repair, silicone weather sealing, and high-rise facade cleaning.",
    "fullDescription": "Commercial showroom facades and glass curtain walls endure relentless wind loads, direct solar UV exposure, and monsoon rainfall. Hind Build provides specialized exterior facade maintenance and engineering fixes. Our certified rope-access and scaffold technicians replace loose or dented Aluminum Composite Panels (ACP), repair broken toughened glass, re-apply weather-grade structural silicone joints, and restore commercial building exteriors.",
    "image": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop",
    "icon": "Building2",
    "features": "[\"Aluminum Composite Panel (ACP) Sheet Replacement & Alignment\",\"Spider Glazing & Toughened Glass Panel Installation\",\"Structural Weather Silicone Joint Removal & Re-Grouting\",\"High-Rise Commercial Facade Washing & Water Ingress Sealing\"]",
    "benefits": "[\"Eliminates hazardous loose ACP panels that can blow off in strong winds\",\"Stops water leakage through exterior curtain wall joints into commercial ceilings\",\"Restores brand prestige and modern corporate exterior appeal for showrooms\",\"Executed by rope-access technicians certified with full safety harnesses\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Elevation Safety & Anchor Audit\",\"desc\":\"Inspecting roof anchor points, aluminum sub-framing, and joint silicon fatigue.\"},{\"step\":\"02\",\"title\":\"Damaged Panel Removal\",\"desc\":\"De-riveting damaged ACP sheets and measuring exact replacement panel sizing.\"},{\"step\":\"03\",\"title\":\"Sub-Frame Rust Treatment\",\"desc\":\"Anti-corrosion coating applied to steel brackets and aluminum runner tracks.\"},{\"step\":\"04\",\"title\":\"New Panel Installation & Riveting\",\"desc\":\"Riveting certified 4mm PVDF coated ACP panels with expansion tolerance.\"},{\"step\":\"05\",\"title\":\"Structural Silicone Weather Sealing\",\"desc\":\"Backer rod insertion and tooling weather-seal silicone along all panel joints.\"}]",
    "warrantyDetails": "3-Year weather sealing warranty on structural silicone joints and ACP panel alignments.",
    "pricingEstimate": "Per sq.ft high-rise rope access audit and fabrication quote based on building elevation.",
    "faqs": "[{\"q\":\"How do you stop rainwater leaking through commercial glass facades?\",\"a\":\"Rainwater leakage occurs when old silicone sealant hardens and pulls away from the glass. We scrape out degraded silicone, insert closed-cell backer rods, and re-grout with non-bleeding structural weather silicone (Dow Corning / GE).\"},{\"q\":\"Can individual damaged ACP sheets be replaced without changing the whole facade?\",\"a\":\"Yes. We measure the exact color shade, sheet thickness (3mm/4mm), and routing profile to replace only the damaged panels seamlessly.\"},{\"q\":\"Do you have safety equipment for high-rise work?\",\"a\":\"Yes. All our facade technicians use certified fall-arrest harnesses, double-rope systems, hard hats, and steel-toed footwear strictly compliant with safety protocols.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80\",\"https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80\",\"https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I need commercial facade repair / ACP sheet replacement / glass sealing.",
    "active": true,
    "order": 18,
    "metaTitle": "Commercial Facade & ACP Glass Work | Hind Build Bhilwara",
    "metaDescription": "ACP panel replacement, spider glazing repairs, and weather silicone sealing in Bhilwara & Rajasthan by Hind Build. Call +91 75970 00601."
  },
  {
    "serviceNumber": "19",
    "title": "Fabrication Work",
    "hindiTitle": "फेब्रिकेशन एवं मेटल वर्क",
    "slug": "fabrication-work",
    "shortDescription": "Mild steel (MS) & stainless steel (SS) railings, safety gates, shed fabrication, welding repairs, and laser-cut screens.",
    "fullDescription": "Sturdy architectural metalwork is essential for boundary security and weather protection. Hind Build delivers precision metal fabrication using high-grade Mild Steel (MS) and 304/316 Stainless Steel (SS). From rooftop terrace polycarbonate sheds and parking canopies to custom laser-cut boundary gates, balcony railings, and on-site welding repairs, our fabricators deliver robust, rust-protected, durable metal craftsmanship.",
    "image": "https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1200&auto=format&fit=crop",
    "icon": "Hammer",
    "features": "[\"304-Grade Stainless Steel & Glass Balcony Railings\",\"Architectural CNC Laser-Cut Boundary Gates & Grilles\",\"Rooftop Sheds, Car Porch & Polycarbonate Canopy Fabrication\",\"On-Site Gas & Arc Welding Structural Repairs\"]",
    "benefits": "[\"Heavy-gauge steel profiles withstand high wind pressure and continuous usage\",\"Multi-coat epoxy zinc phosphate primer protects mild steel against monsoon rust\",\"Argon TIG welding on stainless steel ensures seamless joints without black heat marks\",\"Custom engineering drawings prepared prior to fabrication for perfect fitment\"]",
    "processSteps": "[{\"step\":\"01\",\"title\":\"Site Measurement & Design Mockup\",\"desc\":\"Taking laser measurements and presenting CAD design options for gate or railing profiles.\"},{\"step\":\"02\",\"title\":\"Material Inward & Inspection\",\"desc\":\"Verifying steel wall thickness (gauge) and chemical grade before cutting.\"},{\"step\":\"03\",\"title\":\"Precision Cutting & Welding\",\"desc\":\"Miter cutting and continuous argon TIG or shielded metal arc welding (SMAW).\"},{\"step\":\"04\",\"title\":\"Grinding & Anti-Rust Priming\",\"desc\":\"Seamless joint grinding followed by zinc-chromate anti-corrosion primer application.\"},{\"step\":\"05\",\"title\":\"Site Anchoring & Final Paint\",\"desc\":\"Fastening with heavy anchor bolts into masonry and dual enamel/powder coat finish.\"}]",
    "warrantyDetails": "2-Year structural weld and rust-barrier anti-corrosion primer warranty.",
    "pricingEstimate": "Weight (per kg) or running foot basis with itemized steel grade and paint specifications.",
    "faqs": "[{\"q\":\"What is the difference between 202 and 304 grade stainless steel?\",\"a\":\"202 grade SS contains less nickel and can develop surface rust stains when exposed to outdoor rain and humidity. Hind Build uses genuine 304-grade stainless steel for exterior railings, ensuring zero rusting.\"},{\"q\":\"Can you build a terrace shed that withstands high winds?\",\"a\":\"Yes. Our structural engineers design shed trusses using tubular hollow sections anchored directly into building RCC columns with chemical fasteners, engineered for high wind resistance.\"},{\"q\":\"Do you offer mobile on-site welding for broken gate hinges?\",\"a\":\"Yes. Our mobile welding technicians arrive equipped with portable arc welding units and grinders for fast on-site repairs.\"}]",
    "galleryImages": "[\"https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80\",\"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80\",\"https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80\"]",
    "ogImage": "https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1200&auto=format&fit=crop",
    "whatsappCtaText": "Hello Hind Build, I need fabrication work / shed / gate / railing work at my property.",
    "active": true,
    "order": 19,
    "metaTitle": "Steel Fabrication & Shed Metalwork | Hind Build Bhilwara",
    "metaDescription": "SS railings, laser-cut gates, rooftop sheds, and on-site welding repairs in Bhilwara by Hind Build. Call +91 75970 00601."
  }
];

export async function seedHbsServicesIfEmpty(prisma: any): Promise<number> {
  const count = await prisma.hbsService.count();
  if (count === 0) {
    console.log("[HBS Auto-Seed] Initializing HBS services with rich content...");
    for (const s of HBS_SERVICES_SEED) {
      await prisma.hbsService.upsert({
        where: { slug: s.slug },
        update: s,
        create: s,
      });
    }
    const newCount = await prisma.hbsService.count();
    console.log(`[HBS Auto-Seed] Successfully initialized ${newCount} services.`);
    return newCount;
  }
  return count;
}

export async function seedHbsServicesAlways(prisma: any): Promise<number> {
  console.log("[HBS Seed] Upserting HBS services with rich content...");
  for (const s of HBS_SERVICES_SEED) {
    await prisma.hbsService.upsert({
      where: { slug: s.slug },
      update: s,
      create: s,
    });
  }
  const count = await prisma.hbsService.count();
  console.log(`[HBS Seed] Total active services: ${count}`);
  return count;
}
